Fix: Only one field updates reactively when submitting a SettingsForm with multiple updated fields
CommonsBuild/praise pull request #314
Opened 2022-04-26 18:54 UTC by nebs-dev

Changes inside settings model:
-  the way single setting field is saved
- AllSettings is now selector instead of atom
- added AllSettingIds atom

2022-04-26 20:11 UTC, mattyg commented on packages/frontend/src/model/settings.ts
> +  default: undefined,
Should AllSettingIds default to an empty array instead of undefined? Then we don't need to allow the 'undefined' type.

2022-04-26 20:13 UTC, mattyg commented on packages/frontend/src/model/settings.ts
> +  default: undefined,
actually nevermind i see that's how we're doing it with periods. Let's just keep the same implementations.

2022-04-26 20:18 UTC, mattyg requested changes
Looks like you still need to update the local SingleSetting with the received changes from the api. 

Currently the settings changes are not reflected in the recoil state:
- change two settings, click submit
- navigate to another page
- navigate back to the settings page
*changes to settings are not reflected*
- refresh the page
*changes to settings are reflected*

2022-04-27 07:04 UTC, nebs-dev commented
> Looks like you still need to update the local SingleSetting with the received changes from the api.
> 
> Currently the settings changes are not reflected in the recoil state:
> 
> * change two settings, click submit
> * navigate to another page
> * navigate back to the settings page
>   _changes to settings are not reflected_
> * refresh the page
>   _changes to settings are reflected_
> 
> Otherwise the changes you made look good!

thanks.. i pushed new changes - updated SingleSettings and now that is fixed
But i introduced another bug, something strange is happening with period settings, i will take a look at that also

2022-04-27 17:49 UTC, mattyg commented on packages/frontend/src/model/settings.ts
> +        toast.success(`Saved setting "${response.data.label}"`);
Should this be moved in the conditional above? I.e. only display the success notice if `response.data` is truthy and the local setting is updated?

2022-04-27 17:49 UTC, mattyg approved these changes
:fire: :boom: :100:

2022-04-28 18:27 UTC, merged